baseURL: https://linearfragility.com
languageCode: en
DefaultContentLanguage: en
title: Linear Fragility
theme: anatole
summarylength: 3
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
params:
  author: Linear Fragility
  customCss: []
  customJs: []
  description: Articles with R programming in Tech R, articles about Math and Statistics of real life in Tuesday Writing
  doNotLoadAnimations: no
  favicon: favicons/
  images: 
  keywords: ''
  mainSections: post 青春日记 Tuesday-Writing
  math:
    enable: yes
    use: katex
  profilePicture: images/profile.jpg
  simpleAnalytics: {}
  gtagID: {G-M9S9TJ77JE}
  socialIcons:
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://linkedin.com/in/liwen5
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/li-wen-li
    - icon: fab fa-instagram
      title: instagram
      url: https://www.instagram.com/_7_am
    - icon: fab fa-weixin
      title: Wechat
      url: images/wechat.JPG
  title: Linear Fragility
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 100
    - identifier: posts
      name: Tech R
      url: /post/
      weight: 200
    - identifier: 青春日记
      name: 青春日记
      url: /青春日记/
      weight: 300
    - identifier: Tuesday Writing
      name: Tuesday Writing
      url: /Tuesday-Writing/
      weight: 300
    #- identifier: about
    #  name: About
    #  url: /about/
    #  weight: 300
    #- identifier: contact
    #  name: Contact
    #  url: /contact/
    #  weight: 400
